correction_commit

diff --git a/infrastructure/Jenkinsfile b/infrastructure/Jenkinsfile
--- a/infrastructure/Jenkinsfile
+++ b/infrastructure/Jenkinsfile
@@ -19,22 +19,22 @@ node() {
         sh('''
             #!/bin/bash
 
-            if [ ! -d ${JENKINS_HOME}/project/ansible]; then
+            if [ ! -d ${JENKINS_HOME}/custom-tools]; then
               echo ${JENKINS_HOME}
-              mkdir -p ${JENKINS_HOME}/project/ansible
-              cd ${JENKINS_HOME}/project/ansible
+              mkdir -p ${JENKINS_HOME}/custom-tools
+            fi
+            
+            sudo apt-get update -y
+            sudo apt-get install ansible -y
+            ansible --version
+            if [[ "${?}" -eq 0 ]];
+            then
+                echo 'Ansible Installation Completed'
+            else
+                echo 'Ansible Installation Failed'
+                exit 1
             fi
         ''')
-
-        dir(workspace) {
-           sh ('''
-              #!/bin/bash
-              sudo curl -O https://bootstrap.pypa.io/get-pip.py
-              python get-pip.py
-              pip install ansible --upgrade
-              ansible --version
-        ''')
-        }
     }
 
   stage('Execute Playbook'){
